### ISSUE TITLE
这个库还在继续维护吗!响应式UI同步貌似出了问题

### ISSUE THREAD

**Issue by itmanyong** [lei4519/enhance-weapp#1]
![image](https://user-images.githubusercontent.com/53500371/139522210-9a6d7a1f-0c03-48cb-95be-d7d811b46d62.png)
rutusuoshi如图所示,count的变化未曾响应到界面上

**Comment by lei4519** [comment]
是文档中的示例没有说清楚，已经补充。
需要在 app.js 中调用 Eapp 方法，Epage 才能正常工作。
